(require 'multiple-cursors)
(require 'smartrep)

(declare-function smartrep-define-key "smartrep")

(smartrep-define-key global-map "C-c M"
					 '(("l"		   . 'mc/edit-lines)
					   ("r"		   . 'mc/mark-all-in-region)
					   ("n"        . 'mc/mark-next-like-this)
					   ("p"        . 'mc/mark-previous-like-this)
					   ("m"        . 'mc/mark-more-like-this-extended)
					   ("u"        . 'mc/unmark-next-like-this)
					   ("U"        . 'mc/unmark-previous-like-this)
					   ("s"        . 'mc/skip-to-next-like-this)
					   ("S"        . 'mc/skip-to-previous-like-this)
					   ("*"        . 'mc/mark-all-like-this)
					   ("d"        . 'mc/mark-all-like-this-dwim)
					   ("i"        . 'mc/insert-numbers)
					   ("o"        . 'mc/sort-regions)
					   ("O"        . 'mc/reverse-regions)))
